### ISSUE TITLE
your greed decode implement is wrong. 

### ISSUE THREAD

**Issue by Duum** [HawkAaron/RNN-Transducer#1]
I think your transducer  greed decode implement is wrong.
here is[ my implement of pytorch](https://github.com/sequence-labeling/transducer_greed_decoder).

**Comment by HawkAaron** [comment]
Its based on the assumption that for each acoustic feature frame, there is at most one corresponding label, so we just need to move one step up, then turn right.

I implemented the greedy decode several weeks ago as your way, but the PER is worse in TIMIT.

The decoding algorithm is still under developing, so any comments are welcome.

**Comment by Duum** [comment]
but in my dataset my greedy decode implement CER is 15% lower than yours.

**Comment by HawkAaron** [comment]
Which dataset did you use? 

I'll check that again in TIMIT.

**Comment by Duum** [comment]
In the paper of alex grave, in a transducer path ，only  the label is null, the frame will step. when the label is not null ,the U will increase,But the T will stop to wait.

**Comment by Duum** [comment]
in my private dataset，only when use the second method ，the rnn transducer will compare with ctc.

**Comment by HawkAaron** [comment]
@Duum 
Yes, when non-null is predicted, u forward one step and t stop. But as what I said, at any frame t, the corresponding label will not be more than 1, so if non-null is predicted at frame t, it must move to the next frame after the next prediction. What I said is based on the physical meaning of speech feature. But according to the original transducer model definition, at any time t, there could be more than one up transitions, which is meanless in speech recognition.

I'll check your implementation and reply to you asap.

**Comment by HawkAaron** [comment]
@Duum By the way, what you mean "the second method" ? Have you ever try beam search ?

**Comment by Duum** [comment]
the second method is my implement of greedy decode，I haven't use beam search for now .
a frame corresponding to a label may be just your assumption. If the frame is between two phones, it is possible to have two phones in one frame.

**Comment by HawkAaron** [comment]
@Duum  Thanks for your comments, I'll check that.
