### ISSUE TITLE
Put the testing process to gpu

### ISSUE THREAD

**Issue by yannhan** [HawkAaron/RNN-Transducer#12]
Hi, @HawkAaron , have you tried to put the testing process to gpu? Since for beam search way, it will take much time is the beam size is big. I have tried to modify the code. But there exists some error. I changed the context = mx.cpu(0) to context = mx.gpu(0). 
<img width="1212" alt="WeChat3fcc09c08ea74bfd3fcd507e7b656b79" src="https://user-images.githubusercontent.com/43621476/56260698-d4554200-609d-11e9-9fed-61c2f041ff92.png">

**Comment by HawkAaron** [comment]
Now you can run `eval.py` on gpu with `--cuda` option.

**Comment by yannhan** [comment]
Thanks for your help, but it seems that two lines that you modified in model.py is not correct. Which https://github.com/HawkAaron/RNN-Transducer/blob/f1d535d8b4b264e395e63fead5b9a5e5bb479562/model.py#L108 and   https://github.com/HawkAaron/RNN-Transducer/blob/f1d535d8b4b264e395e63fead5b9a5e5bb479562/model.py#L96. mx.nd.one_hot doesn't have argument for ctx. So I changed it as .as_in_context(ctx). Now it works.

BTW, in your source code, can I train seq2seq with attention model? How about testing? In your eval.py, it seems that it can only test transducer or CTC.

**Comment by HawkAaron** [comment]
seq2seq doesn't work well, maybe you can try other tools.

**Comment by yannhan** [comment]
But I think the code is right, you mean the result is not that good, right?

**Comment by HawkAaron** [comment]
Yeah, I haven't tune the model, maybe you can have a try.

**Comment by yannhan** [comment]
okay!
