### ISSUE TITLE
Phoneme Mapping

### ISSUE THREAD

**Issue by chocolate9624** [HawkAaron/RNN-Transducer#15]
It seems you map all the label to 48 classes. 
https://github.com/HawkAaron/RNN-Transducer/blob/786fa75ff65c8ce859183d3c67aa408ff7fdef13/DataLoader.py#L6

But the number of classes is 62 in Transducer setting.  Is it true ? Thanks !

**Comment by suenyandan** [comment]
I am confused about this too. Since you have closed this issue without getting any response, you have any idea?

**Comment by chocolate9624** [comment]
@suenyandan look at this issue: https://github.com/HawkAaron/RNN-Transducer/issues/4
