### ISSUE TITLE
where is model2012 from

### ISSUE THREAD

**Issue by rzcwade** [HawkAaron/RNN-Transducer#3]
Hi @HawkAaron ,

I was trying to run the eval.py and realized that no module named 'model2012'. Could you let me know where I can import this module?

Thanks!

**Comment by rzcwade** [comment]
I am assuming it's just from your model.py, right?

**Comment by HawkAaron** [comment]
Yes, it should be 'model.py'

**Comment by rzcwade** [comment]
Thanks, @HawkAaron !
