### ISSUE TITLE
model structure Json file

### ISSUE THREAD

**Issue by rzcwade** [HawkAaron/RNN-Transducer#5]
Hi @HawkAaron ,

Thanks for your help with training the network. I am trying to extract the model structure Json file with corresponding parameters files. Since I am new to MXnet and HybridBlock was not used for building the network, do you have a work-around to save the model structure?

I understand this is not RNN-T related issue and I would appreciate it a lot if you could offer some insights.

Thanks.

**Comment by HawkAaron** [comment]
Maybe you can export model as ONNX, and use it in pytorch/mxnet/.... 
Or you can use tensorflow graph to train your model.
If you really want to init model or load model use a json file, then how about write your own custom model structure json format.

**Comment by rzcwade** [comment]
Thanks, @HawkAaron ! Those are great suggestions! I think writing the custom json file should be the way to go. Really appreciate your feedback!
