### ISSUE TITLE
Pre-training LM

### ISSUE THREAD

**Issue by rzcwade** [HawkAaron/RNN-Transducer#6]
Hi @HawkAaron ,

I am trying out pre-training acoustic and prediction models separately. Could you share about how you trained the prediction model independent of RNN-T model and what the data set you used for that?

Thanks!

**Comment by HawkAaron** [comment]
The prediction model is similar to a language model, its actually phone language model for TIMIT dataset.
First add `<SOS>` `<EOS>` to each transcription, here I would like to use `blank` label as both `<SOS>` and `<EOS>`. 
The input of prediction model is a sequence of phones with `blank` label prepended, the output should be the corresponding phone sequence with `blank` appended.

In one word, the training stage is same to language model, except it has a `blank` label.

**Comment by rzcwade** [comment]
Thanks for your prompt response. Just a follow up question, if I were to train character-wise LM, for instance: for a sentence like "hello world", should I send the following as input:
<blank> h e l l o <space> w o r l d 
and the following as target:
h e l l o <space> w o r l d <blank>

I really appreciate your answer!

**Comment by HawkAaron** [comment]
Well, for rnn-transducer, like CTC, it introduced a `blank` label, so you need to send the following as input (`_` means `blank`) :
`_ h e l l o w o r l d`
and the following as the target:
`h e l l o w o r l d _`

**Comment by rzcwade** [comment]
Somehow the blank tag got dropped in my post :( 
Yes, I meant by your response. Thanks a lot!
