### ISSUE TITLE
Dataset and run.sh

### ISSUE THREAD

**Issue by yannhan** [HawkAaron/RNN-Transducer#8]
Excuse me, could you show how to use the Kaldi-timit scripts in your source code?

**Comment by HawkAaron** [comment]
Change the [timit path](https://github.com/HawkAaron/RNN-Transducer/blob/graves2013/run.sh#L38) to your own location, then run `run.sh`, you will get the 41-dim log-mel filter-bank feature with anergy.

`feature_transform.sh` here is to calculate the global cmvn stats using 3 window context on 41-dim feature with delta and delta-delta.

**Comment by yannhan** [comment]
So I need to install Kaldi first?

**Comment by HawkAaron** [comment]
Yeah, kaldi is necessary to reproduce the results exactly. But it only used for feature extraction, maybe librosa is easier to use.

**Comment by yannhan** [comment]
Thanks, HawkAaron, I have extracted the features, but during trainning, I came across this bug : 
![Screenshot from 2019-04-15 01-07-49](https://user-images.githubusercontent.com/43621476/56110709-186c0980-5f1b-11e9-8e7d-86e8415467e1.png)
I used the other datasets, maybe this is the problem. But I can't use TIMIT since this dataset is not free. I don't know why the dimension is not correct. The batch size is 1, the input feature dimension of one sample is 199x90, the label dimension is 21x1. Both type are np.array.

**Comment by HawkAaron** [comment]
The batch dimension for input and label should be the same. For your example, the input should be shaped [1, 199, 90], the label should be shaped [1, 21]. Both are mxnet ndarray.

**Comment by yannhan** [comment]
I modified the type, but the bug still exists.
<img width="1438" alt="WeChat18f137c7048732a069c15023ae697b86" src="https://user-images.githubusercontent.com/43621476/56115059-27a58400-5f28-11e9-989f-8c47a725a22f.png">

**Comment by HawkAaron** [comment]
Could you show me the inputs' shapes before the [loss function call](https://github.com/HawkAaron/RNN-Transducer/blob/graves2013/model.py#L78) ?

**Comment by yannhan** [comment]
Okay, the first figure is the corresponding code, the second is the output. Is that you wa
<img width="928" alt="WeChata433b9baa28a188b4bacf7ef38834210" src="https://user-images.githubusercontent.com/43621476/56115979-49a00600-5f2a-11e9-8d17-bc1450736975.png">
<img width="1439" alt="WeChat820722317e37a02c091df5b5e012edca" src="https://user-images.githubusercontent.com/43621476/56115983-4c9af680-5f2a-11e9-8a7e-b2e1a9372fdb.png">

nt?

**Comment by yannhan** [comment]
BTW, I also found another thing. In the code, f and g should have the same size except the last dim, right? But I found f and g are same size including the last dim....
<img width="929" alt="WeChat674f191c9e20076543460034a2eaa584" src="https://user-images.githubusercontent.com/43621476/56116154-c29f5d80-5f2a-11e9-9c95-9e901e85eb48.png">
<img width="1439" alt="WeChat560c57e01fe10e7d29718a864c159523" src="https://user-images.githubusercontent.com/43621476/56116159-c501b780-5f2a-11e9-8036-e659d10a6a24.png">

**Comment by HawkAaron** [comment]
I have updated the code, you can try it now.

**Comment by yannhan** [comment]
Thanks very much!

**Comment by AtefehSamadi** [comment]
Hi,
I'm very new in this field. Could you please help me how can I download the TIMIT dataset?
I tried to download the dataset from (https://catalog.ldc.upenn.edu/LDC93S1), but unfortunately I can't find the download link.
Could you please help me
Thanks in advance
Atefeh
