### ISSUE TITLE
src/operator/rnn.cc:254:30: error: ‘kCuDNNDropoutDesc’ is not a member of ‘mxnet::ResourceRequest’

### ISSUE THREAD

**Issue by Marcovaldong** [HawkAaron/RNN-Transducer#9]
CentOS 7 + CUDA8.0 + CuDNN 6.0.21 

When I reinstall MxNet with source code and make it, I got the current error. There is nothing about it on the Internet, Can you help me? 

g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/disk2/dongsq/asr/mxnet/3rdparty/mshadow/ -I/disk2/dongsq/asr/mxnet/3rdparty/dmlc-core/include -fPIC -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/nnvm/include -I/disk2/dongsq/asr/mxnet/3rdparty/dlpack/include -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_MKLDNN=1 -DUSE_MKL=1 -I/disk2/dongsq/asr/mxnet/src/operator/nn/mkldnn/ -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/disk2/dongsq/environments/OpenCV-3.4.6/include/opencv -I/disk2/dongsq/environments/OpenCV-3.4.6/include   -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/disk2/dongsq/asr/mxnet/3rdparty/nvidia_cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/convolution_v1.cc -o build/src/operator/convolution_v1.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/disk2/dongsq/asr/mxnet/3rdparty/mshadow/ -I/disk2/dongsq/asr/mxnet/3rdparty/dmlc-core/include -fPIC -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/nnvm/include -I/disk2/dongsq/asr/mxnet/3rdparty/dlpack/include -I/disk2/dongsq/asr/mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_MKLDNN=1 -DUSE_MKL=1 -I/disk2/dongsq/asr/mxnet/src/operator/nn/mkldnn/ -I/disk2/dongsq/asr/mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/disk2/dongsq/environments/OpenCV-3.4.6/include/opencv -I/disk2/dongsq/environments/OpenCV-3.4.6/include   -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/disk2/dongsq/asr/mxnet/3rdparty/nvidia_cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/spatial_transformer.cc -o build/src/operator/spatial_transformer.o
src/operator/rnn.cc: In lambda function:
src/operator/rnn.cc:254:30: error: ‘kCuDNNDropoutDesc’ is not a member of ‘mxnet::ResourceRequest’
         request.emplace_back(ResourceRequest::kCuDNNDropoutDesc);
                              ^

**Comment by HawkAaron** [comment]
It seems that MXNet only support CUDNN >= 7, please check the [source code](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/resource.h#L47).

**Comment by Marcovaldong** [comment]
> It seems that MXNet only support CUDNN >= 7, please check the [source code](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/resource.h#L47).

Enen, I found it, there seems to have some problem in master branch. I have gitted clone form the v1.1.0 branch from MxNet repo. Thanks for your reply.
